export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const ADD_RESOURCE = 'ADD_RESOURCE';
export const ADD_RESOURCE_SUCCESS = 'ADD_RESOURCE_SUCCESS';
export const ADD_RESOURCE_FAILURE = 'ADD_RESOURCE_FAILURE';

export const GET_RESOURCES = 'GET_RESOURCES';
export const GET_RESOURCES_SUCCESS = 'GET_RESOURCES_SUCCESS';
export const GET_RESOURCES_FAILURE = 'GET_RESOURCES_FAILURE';

export const GET_MY_RESOURCES = 'GET_MY_RESOURCES';
export const GET_MY_RESOURCES_SUCCESS = 'GET_MY_RESOURCES_SUCCESS';
export const GET_MY_RESOURCES_FAILURE = 'GET_MY_RESOURCES_FAILURE';

export const GET_RESOURCE = 'GET_RESOURCE';
export const GET_RESOURCE_SUCCESS = 'GET_RESOURCE_SUCCESS';
export const GET_RESOURCE_FAILURE = 'GET_RESOURCE_FAILURE';

export const UNAUTHENTICATED = 'UNAUTHENTICATED';

export const GET_LINK_METADATA = 'GET_LINK_METADATA';
export const GET_LINK_METADATA_SUCCESS = 'GET_LINK_METADATA_SUCCESS';
export const GET_LINK_METADATA_FAILURE = 'GET_LINK_METADATA_FAILURE';

export const UPDATE_RESOURCE_METADATA = 'UPDATE_RESOURCE_METADATA';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE';

export const GET_USER_PUBLIC_INFO = 'GET_USER_PUBLIC_INFO';
export const GET_USER_PUBLIC_INFO_SUCCESS = 'GET_USER_PUBLIC_INFO_SUCCESS';
export const GET_USER_PUBLIC_INFO_FAILURE = 'GET_USER_PUBLIC_INFO_FAILURE';

export const FOLLOWING_CHANGE = 'FOLLOWING_CHANGE';
export const FOLLOWING_CHANGE_SUCCESS = 'FOLLOWING_CHANGE_SUCCESS';
export const FOLLOWING_CHANGE_FAILURE = 'FOLLOWING_CHANGE_FAILURE';
